#!/usr/bin/env bash
#loops through 1 to 100 checking if the number is a multiple of 3(Fizz), 5(Buzz), or both(FizzBuzz)
for i in {1..100}
do
	if ((i%3==0 && i%5==0))
	then
		echo "FizzBuzz"
	elif ((i%3==0))
	then
		echo "Fizz"
	elif ((i%5==0))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
